// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/Guitarbum722/meetup-client/models"

// Clienter is an autogenerated mock type for the Clienter type
type Clienter struct {
	mock.Mock
}

// Categories provides a mock function with given fields:
func (_m *Clienter) Categories() (*models.Categories, error) {
	ret := _m.Called()

	var r0 *models.Categories
	if rf, ok := ret.Get(0).(func() *models.Categories); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Categories)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventByID provides a mock function with given fields: _a0, _a1
func (_m *Clienter) EventByID(_a0 string, _a1 string) (*models.Event, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.Event
	if rf, ok := ret.Get(0).(func(string, string) *models.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsByGeo provides a mock function with given fields: _a0, _a1, _a2
func (_m *Clienter) EventsByGeo(_a0 string, _a1 string, _a2 string) (*models.Events, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *models.Events
	if rf, ok := ret.Get(0).(func(string, string, string) *models.Events); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Events)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsByGroup provides a mock function with given fields: _a0, _a1, _a2
func (_m *Clienter) EventsByGroup(_a0 string, _a1 []string, _a2 bool) (*models.Events, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *models.Events
	if rf, ok := ret.Get(0).(func(string, []string, bool) *models.Events); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Events)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, bool) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsByGroupID provides a mock function with given fields: _a0, _a1, _a2
func (_m *Clienter) EventsByGroupID(_a0 int, _a1 []string, _a2 bool) (*models.Events, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *models.Events
	if rf, ok := ret.Get(0).(func(int, []string, bool) *models.Events); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Events)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, []string, bool) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByID provides a mock function with given fields: _a0
func (_m *Clienter) GroupByID(_a0 []int) (*models.Groups, error) {
	ret := _m.Called(_a0)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]int) *models.Groups); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByOrganizer provides a mock function with given fields: _a0
func (_m *Clienter) GroupByOrganizer(_a0 []int) (*models.Groups, error) {
	ret := _m.Called(_a0)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]int) *models.Groups); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByURLName provides a mock function with given fields: _a0
func (_m *Clienter) GroupByURLName(_a0 []string) (*models.Groups, error) {
	ret := _m.Called(_a0)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]string) *models.Groups); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByZip provides a mock function with given fields: _a0
func (_m *Clienter) GroupByZip(_a0 int) (*models.Groups, error) {
	ret := _m.Called(_a0)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func(int) *models.Groups); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Member provides a mock function with given fields: _a0
func (_m *Clienter) Member(_a0 int) (*models.Member, error) {
	ret := _m.Called(_a0)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(int) *models.Member); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Members provides a mock function with given fields: _a0
func (_m *Clienter) Members(_a0 int) (*models.Members, error) {
	ret := _m.Called(_a0)

	var r0 *models.Members
	if rf, ok := ret.Get(0).(func(int) *models.Members); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Members)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
