// Code generated by mockery v1.0.0
package mocks

import (
	models "github.com/Guitarbum722/meetup-client/models"
	mock "github.com/stretchr/testify/mock"
)

// Clienter is an autogenerated mock type for the Clienter type
type Clienter struct {
	mock.Mock
}

// Categories provides a mock function with given fields:
func (_m *Clienter) Categories() (*models.Categories, error) {
	ret := _m.Called()

	var r0 *models.Categories
	if rf, ok := ret.Get(0).(func() *models.Categories); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Categories)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByID provides a mock function with given fields: groupIDs
func (_m *Clienter) GroupByID(groupIDs []int) (*models.Groups, error) {
	ret := _m.Called(groupIDs)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]int) *models.Groups); ok {
		r0 = rf(groupIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(groupIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByOrganizer provides a mock function with given fields: organizerIDs
func (_m *Clienter) GroupByOrganizer(organizerIDs []int) (*models.Groups, error) {
	ret := _m.Called(organizerIDs)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]int) *models.Groups); ok {
		r0 = rf(organizerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(organizerIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByURLName provides a mock function with given fields: urlNames
func (_m *Clienter) GroupByURLName(urlNames []string) (*models.Groups, error) {
	ret := _m.Called(urlNames)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func([]string) *models.Groups); ok {
		r0 = rf(urlNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(urlNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupByZip provides a mock function with given fields: zipCode
func (_m *Clienter) GroupByZip(zipCode int) (*models.Groups, error) {
	ret := _m.Called(zipCode)

	var r0 *models.Groups
	if rf, ok := ret.Get(0).(func(int) *models.Groups); ok {
		r0 = rf(zipCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Groups)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(zipCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Member provides a mock function with given fields: memberID
func (_m *Clienter) Member(memberID int) (*models.Member, error) {
	ret := _m.Called(memberID)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(int) *models.Member); ok {
		r0 = rf(memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Members provides a mock function with given fields: groupID
func (_m *Clienter) Members(groupID int) (*models.Members, error) {
	ret := _m.Called(groupID)

	var r0 *models.Members
	if rf, ok := ret.Get(0).(func(int) *models.Members); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Members)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
