// Code generated by mockery v1.0.0
package mocks

import meetup "github.com/briandowns/meetup-client"
import mock "github.com/stretchr/testify/mock"

// Clienter is an autogenerated mock type for the Clienter type
type Clienter struct {
	mock.Mock
}

// Member provides a mock function with given fields: memberID
func (_m *Clienter) Member(memberID int) (*meetup.Member, error) {
	ret := _m.Called(memberID)

	var r0 *meetup.Member
	if rf, ok := ret.Get(0).(func(int) *meetup.Member); ok {
		r0 = rf(memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meetup.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Members provides a mock function with given fields: groupID
func (_m *Clienter) Members(groupID int) (*meetup.Members, error) {
	ret := _m.Called(groupID)

	var r0 *meetup.Members
	if rf, ok := ret.Get(0).(func(int) *meetup.Members); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meetup.Members)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
